[mongo]
uri = "mongodb+srv://harr0006_db_user:H%40rreman123@cluster1.vihi1ie.mongodb.net/elhub?retryWrites=true&w=majority&appName=cluster1"
user = "harr0006_db_user"
password = "H@rreman123"
database = "elhub"
collection = "df"

